// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMM_mf20M0dalJTKx-I6QfQnKESEZelqg',
    appId: '1:1064083970451:web:8056ebb1248472b6c53066',
    messagingSenderId: '1064083970451',
    projectId: 'flash-chatter-75210',
    authDomain: 'flash-chatter-75210.firebaseapp.com',
    databaseURL: 'https://flash-chatter-75210-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flash-chatter-75210.appspot.com',
    measurementId: 'G-8SXJ2GQYYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwxvV1n-irySubOpUDGpIvxmNLQFeSBP4',
    appId: '1:1064083970451:android:a6822b1054962f44c53066',
    messagingSenderId: '1064083970451',
    projectId: 'flash-chatter-75210',
    databaseURL: 'https://flash-chatter-75210-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flash-chatter-75210.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApJXzf73V5v77nnc0lUyruYbVSTh0wMY8',
    appId: '1:1064083970451:ios:555a8ca3e5c92ab2c53066',
    messagingSenderId: '1064083970451',
    projectId: 'flash-chatter-75210',
    databaseURL: 'https://flash-chatter-75210-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flash-chatter-75210.appspot.com',
    iosBundleId: 'com.example.flashChatter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApJXzf73V5v77nnc0lUyruYbVSTh0wMY8',
    appId: '1:1064083970451:ios:555a8ca3e5c92ab2c53066',
    messagingSenderId: '1064083970451',
    projectId: 'flash-chatter-75210',
    databaseURL: 'https://flash-chatter-75210-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flash-chatter-75210.appspot.com',
    iosBundleId: 'com.example.flashChatter',
  );
}
